import type { MetricDefinition } from "./types";

/** P0 / Beta only — Post-Beta and Scale intentionally omitted. */
export const P0_METRICS: MetricDefinition[] = [
  // —— Critical ——
  {
    id: "unsafe_flagged_outputs",
    name: "Unsafe / Flagged Outputs",
    category: "AI Quality",
    priority: "critical",
    kind: "quantitative",
    question: "Is the AI producing harmful responses?",
    formula: "# flagged AI responses",
    source: "App Monitoring / Moderation Logs",
    status: "partial",
    gap: "Input crisis keywords + safety.triggered logs exist in coaching-app-llm. Need output moderation + admin feed of flags.",
  },
  {
    id: "app_crashes",
    name: "App Crashes",
    category: "Operational Stability",
    priority: "critical",
    kind: "quantitative",
    question: "Is the app technically stable?",
    formula: "# crashes / active users",
    source: "App Monitoring",
    status: "blocked",
    gap: "No Crashlytics / Sentry in Flutter yet. Add SDK + DSN, then this card goes live.",
  },
  {
    id: "ai_latency",
    name: "Latency",
    category: "AI Quality",
    priority: "critical",
    kind: "quantitative",
    question: "Is AI producing fast responses?",
    formula: "# seconds to respond (p50 / p95)",
    source: "App Monitoring",
    status: "sql_ready",
    gap: "ai_usage_logs.total_ms exists in coaching-app-llm. Need GET /admin/metrics/latency percentiles.",
  },
  {
    id: "payment_failure_rate",
    name: "Payment Failure Rate",
    category: "Operational Stability",
    priority: "critical",
    kind: "quantitative",
    question: "Are subscriptions functioning correctly?",
    formula: "# failed payments / payment attempts",
    source: "Payments Platform",
    status: "sql_ready",
    gap: "payment_error_log + Stripe webhooks in coaching-app-back. Need success denominator + admin rate endpoint.",
  },
  {
    id: "safeguarding_escalations",
    name: "Safeguarding Escalations",
    category: "Operational Stability",
    priority: "critical",
    kind: "mixed",
    question: "Are serious safety concerns occurring?",
    formula: "# safeguarding incidents raised",
    source: "Support / Moderation Logs",
    status: "partial",
    gap: "safety.triggered can webhook; no durable escalation table or admin list yet.",
  },

  // —— High ——
  {
    id: "onboarding_completion",
    name: "Onboarding Completion %",
    category: "Activation",
    priority: "high",
    kind: "quantitative",
    question: "Can users successfully onboard?",
    formula: "# completing onboarding / # starting onboarding",
    source: "App Analytics",
    status: "sql_ready",
    gap: "initial_form_response + profile.onboardingStep in back. Need funnel aggregate API.",
  },
  {
    id: "first_session_completion",
    name: "% Completing First Coaching Session",
    category: "Journey Completion",
    priority: "high",
    kind: "quantitative",
    question: "Can users complete the core experience?",
    formula: "# completing first session / # starting first session",
    source: "App Analytics",
    status: "sql_ready",
    gap: "test_sessions + session.completed sync. Need first-session KPI definition + endpoint.",
  },
  {
    id: "full_journey_completion",
    name: "% Completing Full Coaching Journey",
    category: "Journey Completion",
    priority: "high",
    kind: "quantitative",
    question: "Can users progress through the intended flow?",
    formula: "# completing full journey / # starting journey",
    source: "App Analytics",
    status: "partial",
    gap: "Journey status model incomplete on back (mostly new→active). Need clear journey_completed signal.",
  },
  {
    id: "dropoff_by_stage",
    name: "Drop-off Points by Stage",
    category: "Journey Completion",
    priority: "high",
    kind: "quantitative",
    question: "Where are users disengaging?",
    formula: "Abandonment at each journey stage",
    source: "App Analytics",
    status: "partial",
    gap: "Stage/substep on sessions exists. Need session.turn + abandonment definition + funnel chart API.",
  },
  {
    id: "session_abandonment",
    name: "Session Abandonment Rate",
    category: "Journey Completion",
    priority: "high",
    kind: "quantitative",
    question: "Are users leaving sessions midway?",
    formula: "# abandoned sessions / # sessions started",
    source: "App Analytics",
    status: "blocked",
    gap: "No session.ended / inactivity timeout. Instrument end-of-session first.",
  },
  {
    id: "sessions_per_user",
    name: "Sessions per User",
    category: "Engagement",
    priority: "high",
    kind: "quantitative",
    question: "Are users returning and engaging repeatedly?",
    formula: "Avg sessions per active user",
    source: "App Analytics",
    status: "sql_ready",
    gap: "Derivable from test_sessions / ai_sync_event. Need aggregate + resume-safe counting.",
  },
  {
    id: "return_d1_d7",
    name: "Return Usage (D1 / D7)",
    category: "Engagement",
    priority: "high",
    kind: "quantitative",
    question: "Are users coming back after first use?",
    formula: "% returning after Day 1 / Day 7",
    source: "App Analytics",
    status: "blocked",
    gap: "Need durable product analytics (PostHog/GA) or session event store for cohorts.",
  },
  {
    id: "repeat_sessions",
    name: "Repeat Coaching Sessions",
    category: "Engagement",
    priority: "high",
    kind: "quantitative",
    question: "Are users continuing the journey?",
    formula: "# users completing more than one session",
    source: "App Analytics",
    status: "sql_ready",
    gap: "sessionNumber on test_sessions. Need KPI endpoint.",
  },
  {
    id: "ai_thumbs",
    name: "Positive vs Negative AI Feedback",
    category: "AI Quality",
    priority: "high",
    kind: "mixed",
    question: "Is the AI experience perceived positively?",
    formula: "Thumbs up/down or session feedback ratings",
    source: "In-App Feedback / Survey",
    status: "blocked",
    gap: "No thumbs UI or event in Flutter / LLM yet.",
  },
  {
    id: "did_this_help",
    name: "“Did This Help You?” Rating",
    category: "AI Quality",
    priority: "high",
    kind: "mixed",
    question: "Do users feel supported effectively?",
    formula: "Post-session rating prompt",
    source: "In-App Feedback / Survey",
    status: "partial",
    gap: "POST /journey/:id/session-feedback exists on back; Flutter submitSessionFeedback is not called. Wire UI + aggregate.",
  },
  {
    id: "broken_repetitive",
    name: "Broken / Repetitive Responses",
    category: "AI Quality",
    priority: "high",
    kind: "mixed",
    question: "Is the AI functioning coherently?",
    formula: "# reported broken or repetitive outputs",
    source: "In-App Feedback / Internal Review",
    status: "partial",
    gap: "Parser fallback exists; no usedFallback emit or user report flow.",
  },
  {
    id: "confusion_points",
    name: "Confusion Points",
    category: "UX Clarity",
    priority: "high",
    kind: "mixed",
    question: "Where are users getting confused?",
    formula: "Repeated exits, pauses, or feedback themes",
    source: "App Analytics + Survey",
    status: "blocked",
    gap: "Needs turn timing (secondsSincePreviousTurn) + exit events.",
  },
  {
    id: "ux_themes",
    name: "Qualitative UX Feedback Themes",
    category: "UX Clarity",
    priority: "high",
    kind: "qualitative",
    question: "What recurring usability feedback exists?",
    formula: "Thematic review of user feedback",
    source: "Survey / Interviews",
    status: "partial",
    gap: "Clarity replays only. Need open-text store + tagging (manual or LLM).",
  },
  {
    id: "login_failures",
    name: "Login Failures",
    category: "Operational Stability",
    priority: "high",
    kind: "quantitative",
    question: "Can users reliably access the platform?",
    formula: "# failed login attempts",
    source: "App Analytics",
    status: "partial",
    gap: "API returns invalid_credentials; no login_attempt audit table. Add append-only log.",
  },
  {
    id: "uptime",
    name: "Downtime / Availability",
    category: "Operational Stability",
    priority: "high",
    kind: "quantitative",
    question: "Is the platform consistently accessible?",
    formula: "% uptime across environments",
    source: "Infrastructure Monitoring",
    status: "partial",
    gap: "Wired via UPTIME_KUMA_HEARTBEAT_URL → Uptime Kuma public status page.",
  },
  {
    id: "would_use_again",
    name: "“Would You Use This Again?”",
    category: "Value Perception",
    priority: "high",
    kind: "mixed",
    question: "Do users want to return?",
    formula: "Post-session / survey prompt",
    source: "Survey",
    status: "blocked",
    gap: "Only in handoff stubs (wouldReturn). Ship prompt in app.",
  },
  {
    id: "perceived_value",
    name: "Perceived Value Feedback",
    category: "Value Perception",
    priority: "high",
    kind: "qualitative",
    question: "Do users feel the experience is valuable?",
    formula: "Open-ended coaching value feedback",
    source: "Survey / Interviews",
    status: "blocked",
    gap: "No survey field / event yet.",
  },
  {
    id: "questionnaire_feedback",
    name: "Questionnaire Feedback",
    category: "User Feedback",
    priority: "high",
    kind: "mixed",
    question: "What do users say in product questionnaires?",
    formula: "Responses from in-product questionnaires",
    source: "In-App Feedback / Survey",
    status: "sql_ready",
    gap: "initial_form_* stores pre-coaching answers. Need admin browse + post-session questionnaires if distinct.",
  },

  // —— Medium ——
  {
    id: "signups",
    name: "# of Sign-ups",
    category: "Activation",
    priority: "medium",
    kind: "quantitative",
    question: "Are users entering the funnel?",
    formula: "Count of completed registrations",
    source: "App Analytics",
    status: "sql_ready",
    gap: "user.createdAt in Better Auth. Need admin count by range.",
  },
  {
    id: "verification_success",
    name: "Account Verification Success",
    category: "Activation",
    priority: "medium",
    kind: "quantitative",
    question: "Are users successfully verifying accounts?",
    formula: "# successful verifications / # verification attempts",
    source: "App Analytics",
    status: "sql_ready",
    gap: "emailVerified on user. Attempt count needs verification send/fail log.",
  },
  {
    id: "time_to_first_session",
    name: "Time to First Session",
    category: "Activation",
    priority: "medium",
    kind: "quantitative",
    question: "How quickly are users engaging?",
    formula: "Time from sign-up to first coaching session",
    source: "App Analytics",
    status: "sql_ready",
    gap: "Join user.createdAt × first session. Need aggregate API.",
  },
  {
    id: "avg_session_length",
    name: "Average Session Length",
    category: "Engagement",
    priority: "medium",
    kind: "quantitative",
    question: "Are users meaningfully engaging?",
    formula: "Avg duration of completed sessions",
    source: "App Analytics",
    status: "blocked",
    gap: "Needs session.ended with duration.",
  },
  {
    id: "support_requests",
    name: "Support Requests",
    category: "UX Clarity",
    priority: "medium",
    kind: "quantitative",
    question: "What are users struggling with?",
    formula: "# support tickets / questions",
    source: "Support Tool / Email",
    status: "sql_ready",
    gap: "support table exists (shell). Count OK; message content still thin.",
  },
  {
    id: "willingness_to_pay",
    name: "Willingness to Pay Indicators",
    category: "Value Perception",
    priority: "medium",
    kind: "mixed",
    question: "Would users pay for this experience?",
    formula: "Pricing/value survey + paid conversion proxy",
    source: "Survey",
    status: "partial",
    gap: "No WTP survey question. Stripe subscription status can proxy conversion only.",
  },
];

export const CATEGORY_ORDER: MetricDefinition["category"][] = [
  "Operational Stability",
  "AI Quality",
  "Activation",
  "Journey Completion",
  "Engagement",
  "UX Clarity",
  "Value Perception",
  "User Feedback",
];
